name: my_webpage
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  go_router: ^14.3.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  flutter_quill: ^10.8.5
  image_picker: ^1.1.2
  universal_html: ^2.2.4
  flutter_quill_extensions: ^10.8.5
  flutter_localization: ^0.2.2
  vsc_quill_delta_to_html: ^1.0.5
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_web_compilers: ^4.0.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sound/night_ambience.mp3
    - assets/fonts/


  fonts:
    - family: Onglyp_determine
      fonts:
        - asset: assets/fonts/Onglyp_determine.ttf

    - family: Onglyp_harunanum
      fonts:
        - asset: assets/fonts/Onglyp_harunanum.ttf

    - family: Onglyp_stardust
      fonts:
        - asset: assets/fonts/Onglyp_stardust.ttf
